## Basic Programming 8

### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1=np.arange(8).reshape(2,4)
mat2=np.random.randint(1,17,8).reshape(2,4)
print(mat1)
print()
print(mat2)
print()

print(np.add(mat1,mat2))

[[0 1 2 3]
 [4 5 6 7]]

[[14 13 15  7]
 [ 2 15 13  5]]

[[14 14 17 10]
 [ 6 20 19 12]]


### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


### 3. Write a Python Program to Transpose a Matrix?

In [4]:
mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
print(mat1.T)

[[1 4 7]
 [2 5 8]
 [4 6 9]]


In [5]:
M = [[2,3,4],
     [4,3,5]]

R= [[0,0],
     [0,0],
     [0,0]]

for i in range(len(M)):
    for j in range(len(M[0])):
        R[j][i] = M[i][j]

In [8]:
for i in R:
    print(i)

[2, 4]
[3, 3]
[4, 5]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [14]:
input_str = 'my name is chitti the robot'

# breakdown the string into a list of words
words = input_str.split()

# sort the list
words.sort()

print("The sorted words are:")
for word in words:
    print(word)

The sorted words are:
chitti
is
my
name
robot
the


### 5. Write a Python Program to Remove Punctuation From a String?

In [15]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")

# remove punctuation from the string
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter some string with panctuationssurprised!,may be we can #sleep & Start *early @tomorrow
surprisedmay be we can sleep  Start early tomorrow
